### ISSUE TITLE
Milestone 2 To Do List

### ISSUE THREAD

**Issue by AbdulSafdar** [UBC-MDS/522_group_38#15]
- [x] Containerize the project with a Dockerfile
- [x] Document how to use and update your container image in your README
- [x] #22
- [x] Add matplotlib - matplotlib=3.9.2 to the environment yaml or to the Dockerfile to force install it
- [x] Add data validation checks to the analysis
- [x] pin versions into environment.yaml
- [x] Proofread
- [x] Submit with new release

**Comment by AbdulSafdar** [comment]
Done with all the tasks
