### ISSUE TITLE
Incorporate feedback from milestone 1 and 2 changes for Milestone 4 

### ISSUE THREAD

**Issue by AbdulSafdar** [UBC-MDS/522_group_38#33]
Milestone 1 Feedback Fixes
- [x] Project Structure : The analysis notebook (.ipynb or .Qmd or *Rmd) should be in a sub-directory called something sensible, such as analysis, src, notebooks, docs, etc, to aid in the discoverability of this file, and related ones. Having too many files in the project root makes the project organization less understandable and can lead to longer activation times to productivity for collaborators (including future you!).
- [x] Readme file : The description of the classification task can be more clear, e.g. we binarized classification for wine quality into either good or poor via a decision tree...etc. You might also benefit by explaining why the analysis is important.
- [x] Code of Conduct : The email under "enforcement" should be tied to the team
- [x] Data folder structure : Raw and processed/intermediate data are mixed in the data directory (they should be in subfolders, or at least clearly labelled).
- [x] Environment : versions are missing from environment files(s) for some R or Python packages
- [x] Abstract / Summary : Quality score statement on good and not good should be consistent in the readme and the analysis notebook. Numeric predictor importance can also be included when mentioning the key findings.
- [x] Introduction : It is unsure to the reader how the cut off was made for good/not good quality for binarization.
- [x] Results : Plots suffer from one or more severe problems. For instance, overplotting, missing legend, small text or no axis labels. Plot labels need work.
- [x]  Descriptions need to be more quantitative with values. Bold words are not necessary, remember to explain in short sentences how you interpret and perform cut offs quantitatively and using what metric.
- [x] Conclusion : Assumptions and limitations of methods and findings are not discussed.

MS 2 Feedback Fixes
- [x] Pin version in dockerfile
- [x] Fix data validation to not violate golden rule

Peer Review Feedback
- [x] License : OSI approved license (The software license already is...)
- [x] Documentation for reporting issues 
- [ ] Code readability, add docstrings and other requirements for making the code easier to interpret
- [ ] Author info for scripts
- [x] Author affiliations in report
- [x] Fix citations
- [x] Fix tense issues in report, stay consistent with one
- [ ] Results folder: split into figures and tables (Maybe at the very end if we have time, but it would be a lot of work as the scripts would need to be modified completely)
- [x] Report : round model accuracy, 
- [x] Improve formatting of tables, generate it such that columns have variable names too. 

General Feedback
- [x] Host the report on GitHub pages
- [x] Modify the makefile to automatically copy the rendered document and name it index.html so it can automatically be changed once changes to the report are pushed to GH pages
- [ ] Move ipynb report to report folder

**Comment by AbdulSafdar** [comment]
Some fixes might have already been done

**Comment by AbdulSafdar** [comment]
Just gathering all the feedback we received from MS1, 2 and peer review to fix up our analysis and project in general

**Comment by AbdulSafdar** [comment]
https://github.com/UBC-MDS/data-analysis-review-2024/issues/10
