### ISSUE TITLE
MS4 To-do

### ISSUE THREAD

**Issue by AbdulSafdar** [UBC-MDS/522_group_38#44]
- [x] Makefile
- [x] Functions for data splitting
- [x] Function for EDA
- [x] function for fitting model
- [x] Make MS1, 2 peer review improvements
- [x] change read me on how to use make
- [x] Add readme to the test folder too

**Comment by AbdulSafdar** [comment]
Last thing left :) @Iskanu93 let me know if you need help with it, just need to move the function into the src folder, call it in the script and write some test cases and test them out. Then we can run make and see if the project is reproducible and submit it
